### ISSUE TITLE
Happy people?

### ISSUE THREAD

**Issue by drphilmarshall** [DrMud/SentimentHackPad#3]
Can we extract (not manually!) the "blame" for each sentence (ie who wrote it)? Really I am interested in the happiness of people, not hacks...

**Comment by piccolomud** [comment]
good point. For the hackpad, we'd simply copy-pasted the entire text, so we lost that information. Once we scrape the text properly, we can see if the "blame" is assigned. Commit messages were straight forward

**Comment by drphilmarshall** [comment]
Yeah - I think we can close this one out, since you did the commit messages analysis which does have easy blame capture.
